### ISSUE TITLE
Support for python 3.10

### ISSUE THREAD

**Issue by sumitsharansatsangi** [purificant/python-paseto#4]
Since python 3.10.0 is now released.  So, please provide a support for it too.
Thank you.

**Comment by purificant** [comment]
v0.5.1 release is now available on PyPi: https://pypi.org/project/python-paseto/
See GitHub release here: https://github.com/purificant/python-paseto/releases/tag/v0.5.1

Thank you for your feedback. :+1:

**Comment by purificant** [comment]
@sumitsharansatsangi Please try 0.5.2

**Comment by purificant** [comment]
@sumitsharansatsangi Glad it works for you!
There was a valid issue with installing 0.5.1 with poetry, which was resolved in 0.5.2 so thank you for reporting this!

In the future the plan is to add periodic automated tests for package install with latest versions of poetry, pip and maybe pipenv to help spot these kind of regressions.
